USE [master]
GO

/****** Object:  Database [TygerBergFoodProject]    Script Date: 2020/09/11 13:09:19 ******/
CREATE DATABASE [TygerBergFoodProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TygerBerg Food project', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.AQEELMAJAL\MSSQL\DATA\TygerBerg Food project.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TygerBerg Food project_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.AQEELMAJAL\MSSQL\DATA\TygerBerg Food project_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TygerBergFoodProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TygerBergFoodProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TygerBergFoodProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TygerBergFoodProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TygerBergFoodProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TygerBergFoodProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET RECOVERY FULL 
GO

ALTER DATABASE [TygerBergFoodProject] SET  MULTI_USER 
GO

ALTER DATABASE [TygerBergFoodProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TygerBergFoodProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TygerBergFoodProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TygerBergFoodProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TygerBergFoodProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TygerBergFoodProject] SET QUERY_STORE = OFF
GO

USE [TygerBergFoodProject]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TygerBergFoodProject] SET  READ_WRITE 
GO


